name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_SP }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to ACR
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}

    - name: Set short git commit SHA
      id: vars
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "::set-output name=short_sha::$calculatedSha"


    - name: Build and push Docker image for Backend
      run: |
        docker build --push -t ${{ secrets.ACR_LOGIN_SERVER }}/pact-backend:${{ steps.vars.outputs.short_sha }} .


    - name: Deploy container app
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az containerapp revision copy -n ${{ secrets.CA_BACKEND_NAME }} \
          -g ${{ secrets.RG_NAME }} --revision-suffix ${{ github.run_id }}-${{ github.run_attempt }}

    # - name: Deploy Container App
    #  uses: azure/container-apps-deploy-action@v1
    #  with:
    #    acrName: ${{ secrets.ACR_NAME }}
    #    containerAppName: ${{ secrets.CA_BACKEND_NAME }}
    #    resourceGroup: ${{ secrets.RG_NAME }}
    #    imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/pact-backend:latest
    #    containerAppEnvironment: ${{ secrets.CAE_NAME }}