name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_SP }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to ACR
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build and push Docker images for Frontend and Backend
      run: |
        docker build --push -t ${{ secrets.ACR_LOGIN_SERVER }}/pact-backend:latest .

    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        acrName: ${{ secrets.ACR_NAME }}
        containerAppName: ${{ secrets.CA_BACKEND_NAME }}
        resourceGroup: ${{ secrets.RG_NAME }}
        imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/pact-backend:latest
